### ISSUE TITLE
Client Crashing

### ISSUE THREAD

**Issue by thiagotigaz** [ClassicUO/ClassicUO#1103]
######################## [START LOG] ########################
ClassicUO [STANDARD_BUILD] - 0.1.3.500
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Protocol: CF_RE, CF_TD, CF_LBR, CF_AOS, CF_SE, CF_SA
ClientFeatures: CLF_CONTEXT_MENU
ClientLockedFeatures: TheSecondAge, Renaissance, ThirdDawn, LordBlackthornsRevenge, AgeOfShadows, SameraiEmpire, MondainsLegacy, Splash9, EleventhAge, StygianAbyss, GothicHousing, RusticHousing
ClientVersion: 117444353

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.UI.Gumps.SplitMenuGump.Dispose()
   at ClassicUO.Game.UI.Gumps.SplitMenuGump..ctor(UInt32 serial, Point offset)
   at ClassicUO.Game.Scenes.GameScene.PickupItemBegin(Item item, Int32 x, Int32 y, Nullable`1 amount, Nullable`1 offset)
   at ClassicUO.Game.Scenes.GameScene.OnMouseDragging()
   at ClassicUO.GameController.HandleSDLEvent(IntPtr userdata, IntPtr ptr)
   at SDL2.SDL.SDL_PollEvent(SDL_Event& _event)
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Client.Run()
   at ClassicUO.Bootstrap.Main(String[] args)

**Comment by andreakarasho** [comment]
Fixed in .600 build. Update your cuo
