### ISSUE TITLE
Launcher killed

### ISSUE THREAD

**Issue by toxygene** [ClassicUO/ClassicUO#1265]
The launcher is crashing immediately after patching every time I start it. I noticed in the logs that a copy of the launcher was added to `/tmp/launcher_update_temp`, so I tried running that and I got an `Illegal instruction (core dumped)` error. I also downloaded the latest Linux x64 version from https://www.classicuo.eu/. When I ran that, I also get the `Illegal instruction (core dumped)` error.

```
jhendric@jhendric-workstation:~/UO/ClassicUO$ ./ClassicUOLauncher 
17:02:39 |  TRACE  | 
================= ClassicUO Launcher Log =================
-OS: linux
-description: Linux 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020
-arch: X64
-processArch: X64
-args: ./ClassicUOLauncher

17:02:39 |  TRACE  | setup FNA env vars
17:02:39 |  TRACE  | starting to load settings
17:02:39 |  TRACE  | loading settings in: /home/jhendric/.config/ClassicUOLauncher/launcher_settings.xml
17:02:40 |  TRACE  | done
17:02:40 |  TRACE  | setup FNA logger functions
17:02:40 |  TRACE  | dllmap initialization
17:02:40 |  TRACE  | Initializing DllMap
17:02:40 |  TRACE  | creating the engine
17:02:40 |  TRACE  | /home/jhendric/UO/ClassicUO/libFNA3D.so.0
17:02:40 |  TRACE  | /home/jhendric/UO/ClassicUO/libSDL2-2.0.so.0
17:02:40 |  TRACE  | SDL backend creation...
17:02:40 |  TRACE  | SDL backend created.
17:02:40 |  TRACE  | running the engine!
17:02:40 |  TRACE  | EXT_swap_control_tear unsupported. Fall back to standard VSync.
17:02:40 |  TRACE  | FNA3D Driver: OpenGL
17:02:40 |  TRACE  | OpenGL Renderer: AMD Radeon (TM) R9 380 Series (TONGA, DRM 3.35.0, 5.4.0-56-generic, LLVM 10.0.0)
17:02:40 |  TRACE  | OpenGL Driver: 4.6 (Compatibility Profile) Mesa 20.0.5
17:02:40 |  TRACE  | OpenGL Vendor: X.Org
17:02:40 |  TRACE  | MojoShader Profile: glsl120
17:02:40 |  TRACE  | EXT_swap_control_tear unsupported. Fall back to standard VSync.
17:02:40 |  TRACE  | ImGui renderer creation...
17:02:40 |  TRACE  | ImGui adding default font
17:02:40 |  TRACE  | ImGui adding custom font
17:02:40 |  TRACE  | ImGui building font atlas
17:02:40 |  TRACE  | ImGui setting style
17:02:41 |  TRACE  | manifest received.
17:02:41 |  TRACE  | manifest downloaded.
17:02:41 |  TRACE  | checking manifest entries with latest release: ClassicUOLauncher-linux-x64-release.zip - [release]
17:02:41 |  TRACE  | entry to update: libtheorafile.so - 0b3c0612951ae6df29eca2b7bed65192
17:02:41 |  TRACE  | entry to update: ClassicUOLauncher - 8a6c23f3621be7d709f1a9b2f59173ff
17:02:41 |  TRACE  | entry to update: libFNA3D.so.0 - 98825f941c3c45ec6e649f3bc2341ce3
17:02:41 |  TRACE  | entry to update: FNA.pdb - e4db3a4e861e43f3d4ebd0c89f4fa998
17:02:41 |  TRACE  | entry to update: libFAudio.so.0 - 75ef0e214f6a74f57ed6ac8796488a5b
17:02:41 |  TRACE  | entry to update: libSDL2-2.0.so.0 - ca23b4068b35b07c77843372d679e6ca
17:02:41 |  TRACE  | entry to update: ClassicUOLauncher.runtimeconfig.json - 719f9c2fdf98220c11990ca931768aee
17:02:41 |  TRACE  | entry to update: ClassicUOLauncher.pdb - ad7742f7385252dfa9d0393a7ee2a9e3
17:02:41 |  TRACE  | entry to update: ClassicUOLauncher.deps.json - 875439151bf29ba5f12ff686fe708517
17:02:41 |  TRACE  | manifest is good. Retain it.
17:02:41 |  TRACE  | manifest received.
17:02:41 |  TRACE  | manifest downloaded.
17:02:41 |  TRACE  | checking manifest entries with latest release: ClassicUO-dev-preview-release.zip - [dev-preview]
17:02:41 |  TRACE  | entry to update: ClassicUO.exe - c6c4f10066c258fac3bf402906514e89
17:02:41 |  TRACE  | manifest is good. Retain it.
17:02:45 |  TRACE  | applying patch: ClassicUOLauncher-linux-x64-release.zip - [release]
17:02:45 |  TRACE  | zip extracting...
17:02:45 |  TRACE  | update already running
17:02:45 |  TRACE  | extraction done!
17:02:45 |  TRACE  | running unix shell cmd: -c "chmod a+rwx /tmp/launcher_update_temp/ClassicUOLauncher"
Killed
jhendric@jhendric-workstation:~/UO/ClassicUO$ /tmp/launcher_update_temp/ClassicUOLauncher 
Illegal instruction (core dumped)
```

**Comment by andreakarasho** [comment]
Try to download the launcher again from https://www.classicuo.eu

**Comment by toxygene** [comment]
> Try to download the launcher again from https://www.classicuo.eu

No luck -- same issue.

```
jhendric@jhendric-workstation:~$ wget https://www.classicuo.eu/launcher/linux-x64/ClassicUOLauncher-linux-x64-release.zip
--2020-12-04 09:13:15--  https://www.classicuo.eu/launcher/linux-x64/ClassicUOLauncher-linux-x64-release.zip
Resolving www.classicuo.eu (www.classicuo.eu)... 89.46.109.66
Connecting to www.classicuo.eu (www.classicuo.eu)|89.46.109.66|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17287575 (16M) [application/zip]
Saving to: ‘ClassicUOLauncher-linux-x64-release.zip’

ClassicUOLauncher-linux-x64-release.zip            100%[===============================================================================================================>]  16.49M  8.10MB/s    in 2.0s    

2020-12-04 09:13:18 (8.10 MB/s) - ‘ClassicUOLauncher-linux-x64-release.zip’ saved [17287575/17287575]

jhendric@jhendric-workstation:~$ mkdir ClassicUOLauncher
jhendric@jhendric-workstation:~$ cd ClassicUOLauncher/
jhendric@jhendric-workstation:~/ClassicUOLauncher$ unzip ../ClassicUOLauncher-linux-x64-release.zip 
Archive:  ../ClassicUOLauncher-linux-x64-release.zip
  inflating: FNA.dll.config          
  inflating: libtheorafile.so        
  inflating: ClassicUOLauncher       
  inflating: libFNA3D.so.0           
  inflating: FNA.pdb                 
  inflating: libFAudio.so.0          
  inflating: libSDL2-2.0.so.0        
  inflating: ClassicUOLauncher.runtimeconfig.json  
  inflating: libcimgui.so            
  inflating: ClassicUOLauncher.pdb   
  inflating: ClassicUOLauncher.deps.json  
  inflating: libtinyfiledialogs.so   
jhendric@jhendric-workstation:~/ClassicUOLauncher$ chmod +x ClassicUOLauncher
jhendric@jhendric-workstation:~/ClassicUOLauncher$ ./ClassicUOLauncher 
Illegal instruction (core dumped)
```

**Comment by toxygene** [comment]
Here's the gdb output, in case it's helpful.

```
(gdb) run
Starting program: /home/jhendric/ClassicUOLauncher/ClassicUOLauncher 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd7370700 (LWP 22437)]
Thread 1 "ClassicUOLaunch" received signal SIGILL, Illegal instruction.
0x00000000006e4379 in S_P_CoreLib_System_SpanHelpers__IndexOf_0 (searchSpace=@0x7fffffffe812: 47 '/', value=0 '\000', length=2147483647)
    at /_/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs:348
348	/_/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs: No such file or directory.
(gdb) bt
#0  0x00000000006e4379 in S_P_CoreLib_System_SpanHelpers__IndexOf_0 (searchSpace=@0x7fffffffe812: 47 '/', value=0 '\000', length=2147483647)
    at /_/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs:348
#1  0x00000000006a0e7d in String__Ctor_3 (value=0x7fffffffe812 "/home/jhendric/ClassicUOLauncher/ClassicUOLauncher") at /_/src/libraries/System.Private.CoreLib/src/System/String.cs:189
#2  0x000000000078f9be in S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeCommandLineArgs (argc=1, argv=0x7fffffffe5f8)
    at /_/src/coreclr/src/nativeaot/System.Private.CoreLib/src/Internal/Runtime/CompilerHelpers/StartupCode/StartupCodeHelpers.Extensions.cs:31
#3  0x0000000000c74da1 in ClassicUOLauncher__Module___StartupCodeMain () at <stdin>:15732480
#4  0x000000000041b369 in main (argc=1, argv=0x7fffffffe5f8) at /__w/1/s/src/coreclr/src/nativeaot/Bootstrap/main.cpp:186
```

**Comment by andreakarasho** [comment]
the tmp path is where cuolauncher stores files to make the selfupdate done.
If you run it from tmp folder and there is a version mismatch, launcher will try to replace itself into temp folder and this will cause an exception. 
I suppose this explains the error you met.

The real issue is about file hashes. Do you want contact me in pvt? You can find me on discord

**Comment by andreakarasho** [comment]
Update: was a .NET bug
