### ISSUE TITLE
Changing client version crashes the game

### ISSUE THREAD

**Issue by jjanow** [ClassicUO/ClassicUO#1393]
When I override the client version on settings.json from 7.0.13.4 to 7.0.90.16, the game crashes when launched.

**To Reproduce**
1. Change the 'clientversion' value in settings.json to 7.0.90.16
2. Launch the game

**Expected behavior**
I expect the game to launch.

**Screenshots**
Crash log:
```
######################## [START LOG] ########################
ClassicUO [DEV_BUILD] - 0.1.8.135 - 07/29/2021 00:43:43
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Shard: 216.52.148.101
ClientVersion: 7.0.13.4

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicAssist.UI.ViewModels.OptionsTabViewModel.Serialize(JObject json) in c:\Projects\ClassicAssist\ClassicAssist\UI\ViewModels\OptionsTabViewModel.cs:line 38
   at ClassicAssist.Data.Options.Save(Options options) in c:\Projects\ClassicAssist\ClassicAssist\Data\Options.cs:line 398
   at Assistant.Engine.OnClientClosing() in c:\Projects\ClassicAssist\ClassicAssist\Engine.cs:line 312
   at ClassicUO.Network.Plugin.OnClosing()
   at ClassicUO.GameController.UnloadContent()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.OnDeviceDisposing(Object sender, EventArgs args)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose(Boolean disposing)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Dispose(Boolean disposing)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.System.IDisposable.Dispose()
   at Microsoft.Xna.Framework.Game.Dispose(Boolean disposing)
   at Microsoft.Xna.Framework.Game.Dispose()
   at ClassicUO.Client.Run()
   at ClassicUO.Bootstrap.Main(String[] args)
######################## [END LOG] ########################
```

**Shard**
 - Name of the shard: Age of Britannia

**Information (please complete the following information):**
 - OS: windows 10, 21H1
 - ClassicUO Version: 7.0.13.4
 - [ ] Using DEV Version? No
 - Launcher: ClassicAssist, latest version

**Additional context**
 - How many clients do you run in parallel: Only 1 at a time.
 - Screen Resolution: 5120x1440 @ 240Hz

**Comment by roxya** [comment]
Step 1 is use a current version of ClassicUO, yours is outdated.

But it seems like a problem with ClassicAssist. If you get the same error after updating ClassicUO, use their GitHub or ask for help in discord.

**Comment by jjanow** [comment]
The versioning is a bit confusing.  I was using the latest version of ClassicUO but I did not realize that I needed to update the OSI client as well.  That is where the 13.4 versioning was coming from.  My problems went away after that was done.  However, the exception I was getting was happening without using ClassicAssist so you may still have a bug in that code.  Anyway, thanks for helping me get my problem sorted.
