### ISSUE TITLE
Could ClassicUO move to .NET 5.0/6.0 ?

### ISSUE THREAD

**Issue by andreakarasho** [ClassicUO/ClassicUO#1408]
Back in the days, ClassicUO was compiled in netcore 2.1. I switched back to net47 because of lack of compatibility, performances were not so great like today, FNA rejected any kind of help when compiling games in netcore and there were not all of these handsome tools around.

# Is moving from net472 to net5+ worth?
Absolutely YES.
Tested the game compiled in net6.0 and i gained something like 50 FPS+ with 15k of objects in screen.
The dotnet team worked so hard in net6.0 and we can se few benchmarks and assembly code: https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/

# Can ClassicUO be a .NET 5.0/6.0 app? 
The answer shortly is yes. 
Also FNA started to [support NET 5](https://github.com/FNA-XNA/FNA/wiki/Appendix-E:-.NET-5--and-NativeAOT) too.
It's very easy to do. Just open the `ClassicUO.csproj` and change this line:
```xml
<TargetFramework>net472</TargetFramework>
```
with
```xml
<TargetFramework>net6.0</TargetFramework>
``` 
and here we go!
but it's necessary to deal with few issues.

# Issue 1: Managed plugins support
I think this is the main issue to deal with.
Today aroud ClassicUO there are mainly 3 assistants, all writtein in netframework 4+, all of them loaded with `Reflection`.
If i just change the runtime target from net472 to net5 or net6, like in the section above, these plugins will stop work because of the framework incompatibility.
I'm sure this is not a good deal for the end user.

## A possible solution to the problem: makes the plugin a little more detached from ClassicUO.
Using `Assembly.Load` makes the managed plugin parts fo the ClassicUO process. Instead we just want a simple library without any domain in common. 
So i invented this [tool](https://github.com/ClassicUO/ManagedPluginPatcher).
The plugin owner has to patch the final plugin assembly with that tool. It makes the `Assistant.Engine.Install(void* ptr)` method callable from the external like a native library. I tested it and works both with a pure AOT compilation and with a simple net5/6 build, BUT DOES NOT WORK WITH NET472. This makes the transition a way harder.

_Why does not work if both ClassicUO and plugin are built with net472?_
The answer is in the first line of this section: REFLECTION!
Both of applications uses the `cuoapi.dll`. That dll contains just delegates and types. It's an helper, nothing more.
So i can rid of it from razor like in this [PR i sent](https://github.com/markdwags/Razor/pull/168), bind the right methods to the plugin api. Everything was ready.
When i started CUO with all of these razor fixes the process stops with an error like: "cannot cast delegate A to delegate B".
The `Marshal.GetDelegateForFunctionPointer<T>` call failed because razor tried to load and cast a classicuo delegate types that is different from the razor one. So i should update the `cuoapi.dll` with the newest plugin api. That means a little bit of work for plugin owners, but could be a step [?].

Edit 1: Function pointers seems to work. I already tried to implement func pointers, but were not stable. This time i maker plugins method as [CDecl]. Let's see.

Edit 2: started funcpointers tests

# Issue 2: Cross platform compatibility
todo

# Issue 3: crossgen compilation? mono? AOT?
todo

**Comment by 3HMonkey** [comment]
Not sure if this is because of switching to NET6 but this error comes up after hitting "apply" when used a slider on the options menu. No matter which one. I tested with all sound sliders and also with video aso.

`
######################## [START LOG] ########################
ClassicUO [STANDARD_BUILD] - 0.1.10.0 - 04/04/2022 15:17:04
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Shard: login.uoMYTEST.com
ClientVersion: 7.0.78.4

Exception:
System.InvalidCastException: Unable to cast object of type 'Microsoft.Xna.Framework.Point' to type 'System.DateTime'.
   at TinyJson.DefaultEncoder.<>c.<ZuluDateEncoder>b__3_0(Object obj, JsonBuilder builder) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Utility\JSON\DefaultEncoder.cs:line 169
   at TinyJson.JsonMapper.EncodeValue(Object value, JsonBuilder builder) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Utility\JSON\JsonMapper.cs:line 161
   at TinyJson.DefaultEncoder.<>c.<GenericEncoder>b__0_0(Object obj, JsonBuilder builder) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Utility\JSON\DefaultEncoder.cs:line 47
   at TinyJson.JsonMapper.EncodeValue(Object value, JsonBuilder builder) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Utility\JSON\JsonMapper.cs:line 161
   at TinyJson.Json.Encode(Object value, Boolean pretty) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Utility\JSON\Json.cs:line 57
   at ClassicUO.Configuration.ConfigurationResolver.Save[T](T obj, String file) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Configuration\ConfigurationResolver.cs:line 80
   at ClassicUO.Configuration.Profile.Save(String path) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Configuration\Profile.cs:line 316
   at ClassicUO.Game.UI.Gumps.OptionsGump.Apply() in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Game\UI\Gumps\OptionsGump.cs:line 4199
   at ClassicUO.Game.UI.Gumps.OptionsGump.OnButtonClick(Int32 buttonID) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Game\UI\Gumps\OptionsGump.cs:line 3400
   at ClassicUO.Game.UI.Controls.Control.OnButtonClick(Int32 buttonID) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Game\UI\Controls\Control.cs:line 806
   at ClassicUO.Game.UI.Controls.Button.OnMouseUp(Int32 x, Int32 y, MouseButtonType button) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Game\UI\Controls\Button.cs:line 290
   at ClassicUO.Game.UI.Controls.Control.InvokeMouseUp(Point position, MouseButtonType button) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Game\UI\Controls\Control.cs:line 555
   at ClassicUO.Game.Managers.UIManager.OnMouseButtonUp(MouseButtonType button) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Game\Managers\UIManager.cs:line 215
   at ClassicUO.GameController.HandleSdlEvent(IntPtr userData, IntPtr ptr) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\GameController.cs:line 549
   at SDL2.SDL.SDL_PollEvent(SDL_Event& _event)
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(Game game, GraphicsAdapter& currentAdapter, Boolean[] textInputControlDown, Int32[] textInputControlRepeat, Boolean& textInputSuppress) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\external\FNA\src\FNAPlatform\SDL2_FNAPlatform.cs:line 792
   at Microsoft.Xna.Framework.Game.RunLoop() in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\external\FNA\src\Game.cs:line 857
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\external\FNA\src\Game.cs:line 414
   at ClassicUO.Client.Run() in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Client.cs:line 86
   at ClassicUO.Bootstrap.Main(String[] args) in C:\Users\wewan\Documents\GitHub\UOMYTESTClassicUO\src\Main.cs:line 247
######################## [END LOG] ########################
`

**Comment by 3HMonkey** [comment]
Update: when selecting any option, also when unselecting an option in login scene the same error occurs.

**Comment by 3HMonkey** [comment]
Update: I replaced TinyJson with System.Text.Json, now it is working great. TinyJson is not compatible with NET6.

**Comment by andreakarasho** [comment]
done
