### ISSUE TITLE
Character creation bug

### ISSUE THREAD

**Issue by ghost** [ClassicUO/ClassicUO#187]
Client 7.0.59.8 on UODreams

After selecting the customs skills on character creation   
![crashcharcreation](https://user-images.githubusercontent.com/37397739/49403867-24b2af80-f74e-11e8-84bc-77851b6aa910.jpg)

the client crash.

here the log : 

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=ClassicUO
  StackTrace:
   at ClassicUO.Game.Gumps.UIGumps.CharCreation.CreateCharTradeGump.OnButtonClick(Int32 buttonID) in C:\Users\julie\Documents\ClassicUO\src\Game\Gumps\UIGumps\CharCreation\CreateCharTradeGump.cs:line 160
   at ClassicUO.Game.Gumps.Controls.GumpControl.OnButtonClick(Int32 buttonID) in C:\Users\julie\Documents\ClassicUO\src\Game\Gumps\Controls\GumpControl.cs:line 782
   at ClassicUO.Game.Gumps.Controls.Button.OnMouseClick(Int32 x, Int32 y, MouseButton button) in C:\Users\julie\Documents\ClassicUO\src\Game\Gumps\Controls\Button.cs:line 220
   at ClassicUO.Game.Gumps.Controls.GumpControl.InvokeMouseClick(Point position, MouseButton button) in C:\Users\julie\Documents\ClassicUO\src\Game\Gumps\Controls\GumpControl.cs:line 590
   at ClassicUO.Game.Gumps.UIManager.<.ctor>b__11_2(Object sender, EventArgs e) in C:\Users\julie\Documents\ClassicUO\src\Game\Gumps\UIManager.cs:line 103
   at ClassicUO.Utility.Exstentions.Raise(EventHandler handler, Object sender) in C:\Users\julie\Documents\ClassicUO\src\Utility\Exstentions.cs:line 37
   at ClassicUO.Input.InputManager.HookFunc(IntPtr userdata, IntPtr ev) in C:\Users\julie\Documents\ClassicUO\src\Input\InputManager.cs:line 376
   at SDL2.SDL.SDL_PollEvent(SDL_Event& _event)
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Bootstrap.Main(String[] args) in C:\Users\julie\Documents\ClassicUO\src\Bootstrap.cs:line 59

Using Windows 10 X64

**Comment by SaschaKP** [comment]
fixed
