### ISSUE TITLE
Chat Issues

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#201]
- "Message Party" (in the gump) doesn't do anything
- Once you initiate "Party /" or "Guild \\" chat you cannot quickly switch to the other (when nothing is written) have to backspace to close the chat prefix
- Pasting an image from clipboard crashes client

```System.ArgumentNullException: Array cannot be null.
Parameter name: chars
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount)
   at SDL2.SDL.UTF8_ToManaged(IntPtr s, Boolean freePtr)
   at ClassicUO.Game.UI.Controls.TextBox.OnKeyDown(SDL_Keycode key, SDL_Keymod mod) in C:\Users\aclar\Documents\GitHub\ClassicUO\src\Game\UI\Controls\TextBox.cs:line 157
   at ClassicUO.Game.Managers.UIManager.<.ctor>b__9_8(Object sender, SDL_KeyboardEvent e) in C:\Users\aclar\Documents\GitHub\ClassicUO\src\Game\Managers\UIManager.cs:line 214
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in C:\Users\aclar\Documents\GitHub\ClassicUO\src\Utility\Exstentions.cs:line 43
   at ClassicUO.Input.InputManager.HookFunc(IntPtr userdata, IntPtr ev) in C:\Users\aclar\Documents\GitHub\ClassicUO\src\Input\InputManager.cs:line 118
   at SDL2.SDL.SDL_PollEvent(SDL_Event& _event)
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in C:\Users\aclar\Documents\GitHub\ClassicUO\src\Engine.cs:line 222```

**Comment by markdwags** [comment]
Pasting an image from clipboard crashes client has been addressed in pull #204
