### ISSUE TITLE
clicking "Screenshot" in UOA crasshes

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#322]
the app is defaulted to a developers profile:
c:\users\andre\pictures\razorscreenshots

This can be reproduced by launching Classic UO's UO Assistant app > click screenshots menu (and don't be one of the developers referenced in the errors D:\progetti or "andre" which are not me/my users)

when clicked for other users it crashes . Please note the folders below reference users not on my machine, they appear to be developers and these references need to be updated possibly in the code to prevent crashing:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.UI.Gumps.QuestArrowGump.Update(Double totalMS, Double frameMS) in D:\Progetti\ClassicUO\client\src\Game\UI\Gumps\QuestArrowGump.cs:line 54
   at ClassicUO.Game.Managers.UIManager.Update(Double totalMS, Double frameMS) in D:\Progetti\ClassicUO\client\src\Game\Managers\UIManager.cs:line 640
   at ClassicUO.Engine.Update(GameTime gameTime) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 515
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 257
`

'System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.Network.NetClient.ExtractPackets() in D:\Progetti\ClassicUO\client\src\Network\NetClient.cs:line 262
   at ClassicUO.Network.NetClient.ProcessRecv(SocketAsyncEventArgs e) in D:\Progetti\ClassicUO\client\src\Network\NetClient.cs:line 401
   at ClassicUO.Network.NetClient.IO_Socket(Object sender, SocketAsyncEventArgs e) in D:\Progetti\ClassicUO\client\src\Network\NetClient.cs:line 335
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
'

**Comment by oroechimaru** [comment]
version:
https://github.com/andreakarasho/ClassicUO/releases/tag/alpha2

**Comment by oroechimaru** [comment]
clarification "Razor"

**Comment by oroechimaru** [comment]
this no longer occurs for me in dev 3/14/2019 build .  Was this intentionally fixed or is it working for others too?
