### ISSUE TITLE
UO Outlands sever down > crash to desktop during server maintenance

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#329]
**Describe the bug**
When the server disconnected for maintenance, Classic UO crashed to desktop

**Expected behavior**
- internalize errors > not crash
- do a begin try/catch around the client code or errors and write to log > try to stop the command internally and escape the user to prevent crash (block command?)

SUGGESTION:
a. update developer folder references to %USERPROFILE% and the client folder
b. create an installer that configs/creates folders and permissions for the classic uo client
c. have the client also ask the user questions for their client install folder (UO Outlands for instance) > read the client file to determine client version > update the session file

Possible bug: 
the game seems to reference "Developer gump files" that do not exist in the player's folder
- possible extract/include the files in the ClassicUO installer package (do a search on D:\progetti)

- similar issues also occur when you see error dumps that reference another developer's folders, this is another example found in log/crash errors:
**c:\users\andre\pictures\razorscreenshots**

```System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.UI.Gumps.QuestArrowGump.Update(Double totalMS, Double frameMS) in **D:\Progetti\ClassicUO\client\src\Game\UI\Gumps\QuestArrowGump.cs:lin**e 54
   at ClassicUO.Game.Managers.UIManager.Update(Double totalMS, Double frameMS) in D:\Progetti\ClassicUO\client\src\Game\Managers\UIManager.cs:line 640
   at ClassicUO.Engine.Update(GameTime gameTime) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 515
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 257
```

**Comment by andreakarasho** [comment]
Probably is a null check missing

**Comment by oroechimaru** [comment]
was this fixed? i have not seen "someone elses folder paths" in alpha 3 or the last few dev versions. i did not crash last night during the outage however it may be worth confirming with someone online during patch/server reboot.

**Comment by oroechimaru** [comment]
can someone help test during next outsge if you crash when server goes down while logged in? hoping its fixed

**Comment by oroechimaru** [comment]
I captured it today.

```System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.UI.Gumps.QuestArrowGump.Update(Double totalMS, Double frameMS)
   at ClassicUO.Game.Managers.UIManager.Update(Double totalMS, Double frameMS)
   at ClassicUO.Engine.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args)

System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.UI.Gumps.QuestArrowGump.Update(Double totalMS, Double frameMS)
   at ClassicUO.Game.Managers.UIManager.Update(Double totalMS, Double frameMS)
   at ClassicUO.Engine.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args)

```

**Comment by andreakarasho** [comment]
Ok, got it

**Comment by zolter** [comment]
When I create reconnect, I also ran into this problem too. 

The problem exists in many files due to the lack of checks. For example, the connection may disappear at the time of displaying objects on the screen or receiving a list of objects. I fixed it in many places, but certainly not in all.

**Comment by andreakarasho** [comment]
fixed
