### ISSUE TITLE
Aegis dungeon (uo outlands) crashing on levels 1-2 5+ times yesterday

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#350]
Walking around levels 1 and 2 I crashed multiple times while on USB headset. However Alpha 3 is no longer generating crash logs, and no longer generates errors/logs to the user either it just hard crashes to the desktop (possibly it was recompiled with logging at a lower level than 4? or as non debug build?)

`Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'debug', line 12, position 2.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ClassicUO.Configuration.ConfigurationResolver.Load[T](String file, JsonSerializerSettings jsonsettings)
   at ClassicUO.Engine..ctor(Settings settings)
   at ClassicUO.Engine.Main(String[] args)
`

**Comment by oroechimaru** [comment]
windows events: ( I have .net 4.7.2)
`Application: ClassicUO.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFC267D75F7 (00007FFC26680000) with exit code 80131506.
`

`Faulting application name: ClassicUO.exe, version: 0.0.1.2, time stamp: 0xced34eb1
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffbc72e7bea
Faulting process id: 0x1394
Faulting application start time: 0x01d4d93e335b8165
Faulting application path: C:\Program Files (x86)\Outlands Ultima Online\ClassicUO.exe
Faulting module path: unknown
Report Id: 492a1a6a-8b69-4902-9be8-7d9b29be0272
Faulting package full name: 
Faulting package-relative application ID: `


`Application: ClassicUO.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at ClassicUO.IO.DataReader.ReadUInt()
   at ClassicUO.IO.Resources.AnimationsLoader.TryReadUOPAnimDimension(ClassicUO.IO.Resources.AnimationDirection ByRef)
   at ClassicUO.IO.Resources.AnimationsLoader.LoadDirectionGroup(ClassicUO.IO.Resources.AnimationDirection ByRef, Boolean)
   at ClassicUO.Game.GameObjects.Mobile.ProcessAnimation()
   at ClassicUO.Game.World.Update(Double, Double)
   at ClassicUO.Game.Scenes.GameScene.Update(Double, Double)
   at ClassicUO.Engine.OnUpdate(Double, Double)
   at ClassicUO.Engine.Update(Microsoft.Xna.Framework.GameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Microsoft.Xna.Framework.Game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(System.String[])

`


`Faulting application name: ClassicUO.exe, version: 0.0.1.2, time stamp: 0xced34eb1
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffbc72c7bea
Faulting process id: 0x2db8
Faulting application start time: 0x01d4d93de973a781
Faulting application path: C:\Program Files (x86)\Outlands Ultima Online\ClassicUO.exe
Faulting module path: unknown
Report Id: 8749f86d-70b5-41cf-9bf7-61398c41df3d
Faulting package full name: 
Faulting package-relative application ID: `

`Application: ClassicUO.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at ClassicUO.IO.DataReader.ReadUInt()
   at ClassicUO.IO.Resources.AnimationsLoader.TryReadUOPAnimDimension(ClassicUO.IO.Resources.AnimationDirection ByRef)
   at ClassicUO.IO.Resources.AnimationsLoader.LoadDirectionGroup(ClassicUO.IO.Resources.AnimationDirection ByRef, Boolean)
   at ClassicUO.Game.GameObjects.Mobile.ProcessAnimation()
   at ClassicUO.Game.World.Update(Double, Double)
   at ClassicUO.Game.Scenes.GameScene.Update(Double, Double)
   at ClassicUO.Engine.OnUpdate(Double, Double)
   at ClassicUO.Engine.Update(Microsoft.Xna.Framework.GameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Microsoft.Xna.Framework.Game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(System.String[])

`

`Faulting application name: ClassicUO.exe, version: 0.0.1.2, time stamp: 0xced34eb1
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffbc72b7c4a
Faulting process id: 0x1e08
Faulting application start time: 0x01d4d93db126d80d
Faulting application path: C:\Program Files (x86)\Outlands Ultima Online\ClassicUO.exe
Faulting module path: unknown
Report Id: 15738fa2-6545-4af0-8e0f-cc7992101ff8
Faulting package full name: 
Faulting package-relative application ID: `

`Faulting application name: ClassicUO.exe, version: 0.0.1.2, time stamp: 0xced34eb1
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffbc72e7bea
Faulting process id: 0x334c
Faulting application start time: 0x01d4d9375637bc77
Faulting application path: C:\Program Files (x86)\Outlands Ultima Online\ClassicUO.exe
Faulting module path: unknown
Report Id: 3c3fbf22-59ab-4768-b538-548494ee45d7
Faulting package full name: 
Faulting package-relative application ID: `

`Application: ClassicUO.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at ClassicUO.IO.DataReader.ReadUInt()
   at ClassicUO.IO.Resources.AnimationsLoader.TryReadUOPAnimDimension(ClassicUO.IO.Resources.AnimationDirection ByRef)
   at ClassicUO.IO.Resources.AnimationsLoader.LoadDirectionGroup(ClassicUO.IO.Resources.AnimationDirection ByRef, Boolean)
   at ClassicUO.Game.GameObjects.Mobile.AddLayer(Byte, ClassicUO.Game.Graphic, ClassicUO.Game.Hue, ClassicUO.Game.GameObjects.Mobile, System.Nullable`1<ClassicUO.IO.Resources.EquipConvData>, Boolean, Int32, Boolean)
   at ClassicUO.Game.GameObjects.Mobile.SetupLayers(Byte, ClassicUO.Game.GameObjects.Mobile, Int32 ByRef)
   at ClassicUO.Game.GameObjects.Mobile.Draw(ClassicUO.Renderer.Batcher2D, Microsoft.Xna.Framework.Vector3, ClassicUO.Input.MouseOverList)
   at ClassicUO.Game.Scenes.GameScene.DrawWorld(ClassicUO.Renderer.Batcher2D)
   at ClassicUO.Game.Scenes.GameScene.Draw(ClassicUO.Renderer.Batcher2D)
   at ClassicUO.Engine.Draw(Microsoft.Xna.Framework.GameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Microsoft.Xna.Framework.Game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(System.String[])

`

`Faulting application name: ClassicUO.exe, version: 0.0.1.2, time stamp: 0xced34eb1
Faulting module name: KERNELBASE.dll, version: 10.0.17763.134, time stamp: 0x1659a33b
Exception code: 0xe0434352
Fault offset: 0x0000000000055299
Faulting process id: 0x4f4
Faulting application start time: 0x01d4d86e95150ade
Faulting application path: C:\Program Files (x86)\Outlands Ultima Online\ClassicUO.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 008a1d0c-711e-4055-aa2f-0354e056fa93
Faulting package full name: 
Faulting package-relative application ID: `

`Application: ClassicUO.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Newtonsoft.Json.JsonReaderException
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(System.Object, Newtonsoft.Json.JsonReader, Newtonsoft.Json.Serialization.JsonObjectContract, Newtonsoft.Json.Serialization.JsonProperty, System.String)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty, System.Object)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Newtonsoft.Json.JsonReader, System.Type, Boolean)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(Newtonsoft.Json.JsonReader, System.Type)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(System.String, System.Type, Newtonsoft.Json.JsonSerializerSettings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, Newtonsoft.Json.JsonSerializerSettings)
   at ClassicUO.Configuration.ConfigurationResolver.Load[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, Newtonsoft.Json.JsonSerializerSettings)
   at ClassicUO.Engine..ctor(ClassicUO.Configuration.Settings)
   at ClassicUO.Engine.Main(System.String[])

`

**Comment by oroechimaru** [comment]
This may be related to the audio usb issue although I wasn't switching between audio usb and audio speakers/card at the time. Two folks in discord did 1-3 level run and did not crash.

**Comment by oroechimaru** [comment]
i am going to close this unless it returns. I am testing the recompiled fna file, amd will run around aegis this week on different audio settings. I wasn't crashing after using speakers (not usb)

**Comment by oroechimaru** [comment]
can this be reopened? crashed in 3/24/2019 dev build:

```Exception @ 03-25-19 01:38:34.3554
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.Game.World.RemoveItem(Serial serial) in C:\Users\wonderwoman\Downloads\ClassicUO-dev (8)\ClassicUO-dev\src\Game\World.cs:line 225
   at ClassicUO.Game.World.Update(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev (8)\ClassicUO-dev\src\Game\World.cs:line 128
   at ClassicUO.Game.Scenes.GameScene.Update(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev (8)\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 486
   at ClassicUO.Engine.OnUpdate(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev (8)\ClassicUO-dev\src\Engine.cs:line 657
   at ClassicUO.Engine.Update(GameTime gameTime) in C:\Users\wonderwoman\Downloads\ClassicUO-dev (8)\ClassicUO-dev\src\Engine.cs:line 547
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in C:\Users\wonderwoman\Downloads\ClassicUO-dev (8)\ClassicUO-dev\src\Engine.cs:line 279


Exception @ 03-25-19 01:38:53.4795
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.Game.World.RemoveItem(Serial serial) in C:\Users\wonderwoman\Downloads\ClassicUO-dev (8)\ClassicUO-dev\src\Game\World.cs:line 225
   at ClassicUO.Game.World.Update(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev (8)\ClassicUO-dev\src\Game\World.cs:line 128
   at ClassicUO.Game.Scenes.GameScene.Update(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev (8)\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 486
   at ClassicUO.Engine.OnUpdate(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev (8)\ClassicUO-dev\src\Engine.cs:line 657
   at ClassicUO.Engine.Update(GameTime gameTime) in C:\Users\wonderwoman\Downloads\ClassicUO-dev (8)\ClassicUO-dev\src\Engine.cs:line 547
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in C:\Users\wonderwoman\Downloads\ClassicUO-dev (8)\ClassicUO-dev\src\Engine.cs:line 279
```

**Comment by oroechimaru** [comment]
fixed in 3/25/2019 dev build or i had accidentally broken it via compiler =)
