### ISSUE TITLE
crash picking up recall scrolls from backpack and attempting to place in runebook

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#354]
dev 3/14/19 build:
a. picked up a stack of two recall scrolls > attempted to drop on rune book > crash
b. relaunched > repeated without crash
c. no "log" was generated again, but this time a popup did occur in the client. I'm going to guess  I didn't compile the debug version? 

d. it looks like a "null" catch is possibly needed. I noticed when I run the code analyzer in visual studio, a few recommendations are related to "else" do nothing type statements, possibly that is related ? If not can we replace nulls with a default ?  (I'm a sql coder , so I'm thinking in terms of sql sorry)  

`System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Renderer.SpriteTexture.Contains(Int32 x, Int32 y, Boolean pixelCheck) in C:\Users\wonderwoman\Downloads\ClassicUO-dev20190314\ClassicUO-dev\src\Renderer\SpriteTexture.cs:line 93
   at ClassicUO.Game.UI.Controls.Button.Contains(Int32 x, Int32 y) in C:\Users\wonderwoman\Downloads\ClassicUO-dev20190314\ClassicUO-dev\src\Game\UI\Controls\Button.cs:line 276
   at ClassicUO.Game.UI.Controls.Control.HitTest(Point position) in C:\Users\wonderwoman\Downloads\ClassicUO-dev20190314\ClassicUO-dev\src\Game\UI\Controls\Control.cs:line 495
   at ClassicUO.Game.UI.Controls.Control.HitTest(Point position) in C:\Users\wonderwoman\Downloads\ClassicUO-dev20190314\ClassicUO-dev\src\Game\UI\Controls\Control.cs:line 508
   at ClassicUO.Game.Managers.UIManager.GetMouseOverControl(Point position) in C:\Users\wonderwoman\Downloads\ClassicUO-dev20190314\ClassicUO-dev\src\Game\Managers\UIManager.cs:line 776
   at ClassicUO.Game.Managers.UIManager.HandleMouseInput() in C:\Users\wonderwoman\Downloads\ClassicUO-dev20190314\ClassicUO-dev\src\Game\Managers\UIManager.cs:line 715
   at ClassicUO.Game.Managers.UIManager.Update(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev20190314\ClassicUO-dev\src\Game\Managers\UIManager.cs:line 666
   at ClassicUO.Engine.OnUIUpdate(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev20190314\ClassicUO-dev\src\Engine.cs:line 627
   at ClassicUO.Engine.Update(GameTime gameTime) in C:\Users\wonderwoman\Downloads\ClassicUO-dev20190314\ClassicUO-dev\src\Engine.cs:line 528
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in C:\Users\wonderwoman\Downloads\ClassicUO-dev20190314\ClassicUO-dev\src\Engine.cs:line 270`

windows event:
`Faulting application name: ClassicUO.exe, version: 0.0.1.3, time stamp: 0xde09f028
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffbc75beee6
Faulting process id: 0x43f8
Faulting application start time: 0x01d4db6ce67b1904
Faulting application path: C:\Program Files (x86)\Outlands Ultima Online\ClassicUO.exe
Faulting module path: unknown
Report Id: 8398786e-2369-46a6-ac6b-fa637ceaacfb
Faulting package full name: 
Faulting package-relative application ID: `

'
Application: ClassicUO.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at ClassicUO.Renderer.SpriteTexture.Contains(Int32, Int32, Boolean)
   at ClassicUO.Game.UI.Controls.Button.Contains(Int32, Int32)
   at ClassicUO.Game.UI.Controls.Control.HitTest(Microsoft.Xna.Framework.Point)
   at ClassicUO.Game.UI.Controls.Control.HitTest(Microsoft.Xna.Framework.Point)
   at ClassicUO.Game.Managers.UIManager.GetMouseOverControl(Microsoft.Xna.Framework.Point)
   at ClassicUO.Game.Managers.UIManager.HandleMouseInput()
   at ClassicUO.Game.Managers.UIManager.Update(Double, Double)
   at ClassicUO.Engine.OnUIUpdate(Double, Double)
   at ClassicUO.Engine.Update(Microsoft.Xna.Framework.GameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Microsoft.Xna.Framework.Game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(System.String[])

'

**Comment by oroechimaru** [comment]
I have not been able to reproduce this issue since resolving the audio issues with the updated FNA components.  

devs the client seems much more stable with the new compiled fna file i linked. could you incorporate something similar in dev today? i could then close this . i loaded a dozen recall scrolls without crashing since.

i did not crash at all in any areas after updating fna either last night in six hours (record for me). Let me know if it gets updated I can then retest dev and this can be closed.

**Comment by oroechimaru** [comment]
i read dev notes... fna was refreshed. closing unless returns.
