### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by simarsenault** [ClassicUO/ClassicUO#368]
**Describe the bug**
Sorry, I don't have a clear and concise description as I'm unable to trigger it, but my client often crashes.

**To Reproduce**
Can't reproduce it on-demand, how ever I get this crash every play session.

**Expected behavior**
No crash? :)

**Screenshots**
No screenshot, but I got a stacktrace:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.IO.Resources.FontsLoader.GeneratePixelsUnicode(Byte font, String str, UInt16 color, Byte cell, Int32 width, TEXT_ALIGN_TYPE align, UInt16 flags, Boolean saveHitmap) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\IO\Resources\FontsLoader.cs:line 1334
   at ClassicUO.IO.Resources.FontsLoader.GenerateUnicode(Byte font, String str, UInt16 color, Byte cell, Int32 width, TEXT_ALIGN_TYPE align, UInt16 flags, Boolean saveHitmap) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\IO\Resources\FontsLoader.cs:line 637
   at ClassicUO.Renderer.RenderedText.CreateTexture() in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Renderer\RenderedText.cs:line 191
   at ClassicUO.Renderer.RenderedText.set_Text(String value) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Renderer\RenderedText.cs:line 115
   at ClassicUO.Game.UI.Controls.RenderedTextList.AddEntry(String text, Int32 font, Hue hue, Boolean isUnicode) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Game\UI\Controls\RenderedTextList.cs:line 134
   at ClassicUO.Game.UI.Gumps.JournalGump.AddJournalEntry(Object sender, JournalEntry entry) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Game\UI\Gumps\JournalGump.cs:line 90
   at ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Utility\Exstentions.cs:line 42
   at ClassicUO.Game.Managers.JournalManager.Add(String text, Hue hue, String name, Boolean isunicode) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Game\Managers\JournalManager.cs:line 23
   at ClassicUO.Game.Scenes.GameScene.ChatOnMessage(Object sender, UOMessageEventArgs e) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Game\Scenes\GameScene.cs:line 276
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Utility\Exstentions.cs:line 42
   at ClassicUO.Game.Chat.OnMessage(Entity parent, String text, String name, Hue hue, MessageType type, MessageFont font, Boolean unicode, String lang) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Game\Chat.cs:line 122
   at ClassicUO.Network.PacketHandlers.UnicodeTalk(Packet p) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Network\PacketHandlers.cs:line 2269
   at ClassicUO.Network.PacketHandlers.OnPacket(Object sender, Packet p) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Network\PacketHandlers.cs:line 91
   at ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Utility\Exstentions.cs:line 42
   at ClassicUO.Network.NetClient.Update() in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Network\NetClient.cs:line 254
   at ClassicUO.Engine.OnNetworkUpdate(Double totalMS, Double frameMS) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Engine.cs:line 623
   at ClassicUO.Engine.Update(GameTime gameTime) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Engine.cs:line 538
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in D:\Users\Simon\GitHub\andreakarasho\ClassicUO\src\Engine.cs:line 278
```

**Desktop (please complete the following information):**
 - OS: Windows 10 64bits, fully updated
 - Browser: Chrome 72

**Additional context**
Seems to happen randomly. I'm on the dev branch, commit ea8d3e2aca249f0a665a00032f67bdd918f20227

**Comment by andreakarasho** [comment]
Are you using razor?
Your solution is updated to the latest commit ( https://github.com/andreakarasho/ClassicUO/commit/80a9999b926ab25b98dc71ac47f40f5109ba631d) ?

**Comment by simarsenault** [comment]
Using default settings, so yes Razor is running.

I was on commit ea8d3e2, I'll update tonight and see if it still happens.

**Comment by andreakarasho** [comment]
I d like to try cuo on your shard to replicate the issue. What is the shard name?

btw errors is throwed when you receive an unicodetalk packet

**Comment by andreakarasho** [comment]
should be fixed in dev
