### ISSUE TITLE
Crashed filling donation "Skill book" with a skill scroll

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#377]
Uo outlands: alpha 5

a. placed 1st skill scroll in no prob
b. placed 2nd skill scroll > 3 seconds later I crashed (begging scroll)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.UI.Gumps.HealthBarGump.BuildGump() in D:\Progetti\ClassicUO\client\src\Game\UI\Gumps\HealthBarGump.cs:line 117
   at ClassicUO.Game.Managers.PartyManager.AddPartyMember(Serial mobileSerial) in D:\Progetti\ClassicUO\client\src\Game\Managers\PartyManager.cs:line 169
   at ClassicUO.Game.Managers.PartyManager.ReceiveRemovePartyMember(Serial[] mobileSerials) in D:\Progetti\ClassicUO\client\src\Game\Managers\PartyManager.cs:line 141
   at ClassicUO.Game.Managers.PartyManager.HandlePartyPacket(Packet p) in D:\Progetti\ClassicUO\client\src\Game\Managers\PartyManager.cs:line 92
   at ClassicUO.Network.PacketHandlers.ExtendedCommand(Packet p) in D:\Progetti\ClassicUO\client\src\Network\PacketHandlers.cs:line 2499
   at ClassicUO.Network.PacketHandlers.OnPacket(Object sender, Packet p) in D:\Progetti\ClassicUO\client\src\Network\PacketHandlers.cs:line 89
   at ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in D:\Progetti\ClassicUO\client\src\Utility\Exstentions.cs:line 42
   at ClassicUO.Network.NetClient.Update() in D:\Progetti\ClassicUO\client\src\Network\NetClient.cs:line 260
   at ClassicUO.Engine.OnNetworkUpdate(Double totalMS, Double frameMS) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 736
   at ClassicUO.Engine.Update(GameTime gameTime) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 648
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 291
```

```
Exception @ 03-29-19 03:13:59.0406
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.UI.Gumps.HealthBarGump.BuildGump() in D:\Progetti\ClassicUO\client\src\Game\UI\Gumps\HealthBarGump.cs:line 117
   at ClassicUO.Game.Managers.PartyManager.AddPartyMember(Serial mobileSerial) in D:\Progetti\ClassicUO\client\src\Game\Managers\PartyManager.cs:line 169
   at ClassicUO.Game.Managers.PartyManager.ReceiveRemovePartyMember(Serial[] mobileSerials) in D:\Progetti\ClassicUO\client\src\Game\Managers\PartyManager.cs:line 141
   at ClassicUO.Game.Managers.PartyManager.HandlePartyPacket(Packet p) in D:\Progetti\ClassicUO\client\src\Game\Managers\PartyManager.cs:line 92
   at ClassicUO.Network.PacketHandlers.ExtendedCommand(Packet p) in D:\Progetti\ClassicUO\client\src\Network\PacketHandlers.cs:line 2499
   at ClassicUO.Network.PacketHandlers.OnPacket(Object sender, Packet p) in D:\Progetti\ClassicUO\client\src\Network\PacketHandlers.cs:line 89
   at ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in D:\Progetti\ClassicUO\client\src\Utility\Exstentions.cs:line 42
   at ClassicUO.Network.NetClient.Update() in D:\Progetti\ClassicUO\client\src\Network\NetClient.cs:line 260
   at ClassicUO.Engine.OnNetworkUpdate(Double totalMS, Double frameMS) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 736
   at ClassicUO.Engine.Update(GameTime gameTime) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 648
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 291
```

skill book:
![image](https://user-images.githubusercontent.com/26830362/55207185-2eea3500-51a7-11e9-8ced-a9a7d2690206.png)

**Comment by andreakarasho** [comment]
fixed
