### ISSUE TITLE
Crash/Index out of bounds crash in dev 3/29/2019

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#379]
Collecting random errors in post alpha 5: dev build 3/29/2019

**dev 3/29/2019 build:**
```Exception @ 03-29-19 19:44:21.4043
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.Game.World.RemoveItem(Serial serial) in D:\Progetti\ClassicUO\client\src\Game\World.cs:line 225
   at ClassicUO.Game.World.Update(Double totalMS, Double frameMS) in D:\Progetti\ClassicUO\client\src\Game\World.cs:line 128
   at ClassicUO.Game.Scenes.GameScene.Update(Double totalMS, Double frameMS) in D:\Progetti\ClassicUO\client\src\Game\Scenes\GameScene.cs:line 486
   at ClassicUO.Engine.OnUpdate(Double totalMS, Double frameMS) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 763
   at ClassicUO.Engine.Update(GameTime gameTime) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 653
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 291

```

```
alpha 5 (pre dev 3/29/2019 update):
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.Game.World.RemoveItem(Serial serial) in D:\Progetti\ClassicUO\client\src\Game\World.cs:line 225
   at ClassicUO.Game.World.Update(Double totalMS, Double frameMS) in D:\Progetti\ClassicUO\client\src\Game\World.cs:line 128
   at ClassicUO.Game.Scenes.GameScene.Update(Double totalMS, Double frameMS) in D:\Progetti\ClassicUO\client\src\Game\Scenes\GameScene.cs:line 486
   at ClassicUO.Engine.OnUpdate(Double totalMS, Double frameMS) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 763
   at ClassicUO.Engine.Update(GameTime gameTime) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 653
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 291
```

windows event alpha 5:
```
Faulting application name: ClassicUO.exe, version: 0.0.1.5, time stamp: 0x8dcc2f03
Faulting module name: KERNELBASE.dll, version: 10.0.17763.134, time stamp: 0x1659a33b
Exception code: 0xe0434352
Fault offset: 0x0000000000055299
Faulting process id: 0x2334
Faulting application start time: 0x01d4e6592cab0d1d
Faulting application path: C:\Program Files (x86)\Outlands Ultima Online\ClassicUO.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: ef25c324-827d-4813-92c3-ddaa978e00af
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by andreakarasho** [comment]
fixed
