### ISSUE TITLE
Inferno level 2 crashing: may be pet related or summon related

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#401]
v1.0.1.7:
a. this section of inferno I was crashing hard nonstop.

b. however like Aegis, it may not be the dungeon but "people" in the dungeon. 
- there were summoned earth eles
- black cat tamed pet (high level skills)

c. I crashed a 4-5x
- i found the rekt guys with pets to take screenshots. not sure if its them or inferno.

d. both of us crashed in party on classicuo at the same time multiple times. We then used standard (first screenshot) to get out.

<img width="753" alt="2019-04-03 20_58_17-Clipboard" src="https://user-images.githubusercontent.com/26830362/55524507-42881680-5653-11e9-9c2d-9abadd3a5ae5.png">

<img width="1241" alt="2019-04-03 20_54_28-Start" src="https://user-images.githubusercontent.com/26830362/55524496-34d29100-5653-11e9-912f-56a3c13a3fc2.png">

```
Exception @ 04-04-19 01:51:38.3878
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.Game.World.RemoveItem(Serial serial) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Game\World.cs:line 225
   at ClassicUO.Game.World.Update(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Game\World.cs:line 128
   at ClassicUO.Game.Scenes.GameScene.Update(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 491
   at ClassicUO.Engine.OnUpdate(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Engine.cs:line 767
   at ClassicUO.Engine.Update(GameTime gameTime) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Engine.cs:line 657
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Engine.cs:line 291


Exception @ 04-04-19 01:52:04.1008
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.Game.World.RemoveItem(Serial serial) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Game\World.cs:line 225
   at ClassicUO.Game.World.Update(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Game\World.cs:line 128
   at ClassicUO.Game.Scenes.GameScene.Update(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 491
   at ClassicUO.Engine.OnUpdate(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Engine.cs:line 767
   at ClassicUO.Engine.Update(GameTime gameTime) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Engine.cs:line 657
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Engine.cs:line 291
```

**Comment by oroechimaru** [comment]
```ClassicUO - v0.0.1.5
OS: Win32NT x64

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.Game.World.RemoveItem(Serial serial) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Game\World.cs:line 225
   at ClassicUO.Game.World.Update(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Game\World.cs:line 128
   at ClassicUO.Game.Scenes.GameScene.Update(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 491
   at ClassicUO.Engine.OnUpdate(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Engine.cs:line 767
   at ClassicUO.Engine.Update(GameTime gameTime) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Engine.cs:line 657
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Engine.cs:line 291
```

**Comment by oroechimaru** [comment]
weird it shows v0.0.1.5 in crash log (may be a bug)

```
ClassicUO - v0.0.1.5
OS: Win32NT x64

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.Game.World.RemoveItem(Serial serial) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Game\World.cs:line 225
   at ClassicUO.Game.World.Update(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Game\World.cs:line 128
   at ClassicUO.Game.Scenes.GameScene.Update(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 491
   at ClassicUO.Engine.OnUpdate(Double totalMS, Double frameMS) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Engine.cs:line 767
   at ClassicUO.Engine.Update(GameTime gameTime) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Engine.cs:line 657
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Main(String[] args) in C:\Users\wonderwoman\Downloads\ClassicUO-dev_20190329\ClassicUO-dev\src\Engine.cs:line 291

```

**Comment by andreakarasho** [comment]
Try to run the dev preview of cuo

https://github.com/andreakarasho/ClassicUO/releases/tag/ClassicUO-dev-preview

**Comment by oroechimaru** [comment]
I verified in Dev 0.0.1.81 I no longer crash in inferno. However there were not a lot of pets in the area this morning. There were earth elemental summons like last night and they caused 0 issues. Close?
