### ISSUE TITLE
Running in a vm with very wide display traceback

### ISSUE THREAD

**Issue by credzba** [ClassicUO/ClassicUO#422]
Setup both alpha and dev version with same failure:
System.NotSupportedException
  HResult=0x80131515
  Message=Unrecognized window depth/stencil format!
  Source=FNA
  StackTrace:
   at Microsoft.Xna.Framework.Graphics.OpenGLDevice..ctor(PresentationParameters presentationParameters, GraphicsAdapter adapter)
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateGLDevice(PresentationParameters presentationParameters, GraphicsAdapter adapter)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice()
   at ClassicUO.Engine..ctor(Settings settings)
   at ClassicUO.Engine.Main(String[] args)

Run a vm with resolution of 3500x1000 running windows 7 vm guest on a linux host.

**To Reproduce**
1. unzip files
2. populate settings.json
3. launch ClassicUO.exe

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by andreakarasho** [comment]
3D acceleration enabled?

**Comment by DarkLotus** [comment]
This isn't really a bug, as the first line of your log says "System.NotSupportedException"
Your system does not support the window depth/stencil format used by ClassicUO

**Comment by ndemeshchenko** [comment]
@DarkLotus any idea on how to make it supported?
I clearly see it as a bug, cause application failing with exception without many details.
