### ISSUE TITLE
Skill Button Crashes Program

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#531]
I just started using Alpha 11 and when I use the older skill gump, it crashes CUO. If I use your newer version, it does not crash.

**Comment by andreakarasho** [comment]
Can you explain better ?
Do you have the crash log ?

**Comment by Djeryv** [comment]
`ClassicUO [dev] - v0.1.2.0
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.Game.UI.Gumps.StandardSkillsGump.SkillNameComparer.Compare(Int32 x, Int32 y) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Game\UI\Gumps\StandardSkillsGump.cs:line 212
   at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ClassicUO.Game.UI.Gumps.StandardSkillsGump..ctor() in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Game\UI\Gumps\StandardSkillsGump.cs:line 94
   at ClassicUO.Network.PacketHandlers.UpdateSkills(Packet p) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Network\PacketHandlers.cs:line 1293
   at ClassicUO.Network.PacketHandlers.OnPacket(Object sender, Packet p) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Network\PacketHandlers.cs:line 92
   at ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Utility\Exstentions.cs:line 45
   at ClassicUO.Network.NetClient.Update() in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Network\NetClient.cs:line 243
   at ClassicUO.Engine.OnNetworkUpdate(Double totalMS, Double frameMS) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Engine.cs:line 820
   at ClassicUO.Engine.Tick() in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Engine.cs:line 686
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Run(String[] args) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Engine.cs:line 320
   at ClassicUO.Bootstrap.Main(String[] args) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Main.cs:line 26
ClassicUO [dev] - v0.1.2.0
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.Game.UI.Gumps.StandardSkillsGump.SkillNameComparer.Compare(Int32 x, Int32 y) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Game\UI\Gumps\StandardSkillsGump.cs:line 212
   at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ClassicUO.Game.UI.Gumps.StandardSkillsGump..ctor() in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Game\UI\Gumps\StandardSkillsGump.cs:line 94
   at ClassicUO.Network.PacketHandlers.UpdateSkills(Packet p) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Network\PacketHandlers.cs:line 1293
   at ClassicUO.Network.PacketHandlers.OnPacket(Object sender, Packet p) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Network\PacketHandlers.cs:line 92
   at ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Utility\Exstentions.cs:line 45
   at ClassicUO.Network.NetClient.Update() in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Network\NetClient.cs:line 243
   at ClassicUO.Engine.OnNetworkUpdate(Double totalMS, Double frameMS) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Engine.cs:line 820
   at ClassicUO.Engine.Tick() in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Engine.cs:line 686
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Run(String[] args) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Engine.cs:line 320
   at ClassicUO.Bootstrap.Main(String[] args) in C:\Users\Mangar\Downloads\ClassicUO-fd9b87d5aeb9b0de9381891655c195e5564977d3\src\Main.cs:line 26`

**Comment by Djeryv** [comment]
When I click the paperdoll skill button, the whole client just closes. Above is the crash log I got.

**Comment by andreakarasho** [comment]
shard?

**Comment by Djeryv** [comment]
My own personal shard...so i can dig into things if you need me to.

My client also stripped out Spellweaving and Throwing out of the list so the player never sees those choices. So maybe those are related?

**Comment by andreakarasho** [comment]
I need client files (skills mul expecially)

**Comment by Djeryv** [comment]
Here is the files I changed. If you need the entire client, I can point to the download on ServUO.

[skills.zip](https://github.com/andreakarasho/ClassicUO/files/3318329/skills.zip)

**Comment by andreakarasho** [comment]
fixed lemme know

**Comment by Djeryv** [comment]
So far so good. I can open the old skill gump. I can create a new group in there and add skills. I can do the show REAL button but if I press the SHOW CAP button it will crash and if I try to delete a GROUP it will crash. Here are the last couple of logs when I tried to do this:


ClassicUO [dev] - v0.1.2.0
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.GameObjects.Mobile.DrawInternal(UltimaBatcher2D batcher, Mobile owner, Item entity, Int32 x, Int32 y, Boolean mirror, SByte frameIndex, Boolean hasShadow, UInt16 id, Boolean isParent) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\GameObjects\Views\MobileView.cs:line 266
   at ClassicUO.Game.GameObjects.Mobile.DrawCharacter(UltimaBatcher2D batcher, Int32 posX, Int32 posY) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\GameObjects\Views\MobileView.cs:line 227
   at ClassicUO.Game.GameObjects.Mobile.Draw(UltimaBatcher2D batcher, Int32 posX, Int32 posY) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\GameObjects\Views\MobileView.cs:line 54
   at ClassicUO.Game.Scenes.GameScene.DrawWorld(UltimaBatcher2D batcher) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 669
   at ClassicUO.Game.Scenes.GameScene.Draw(UltimaBatcher2D batcher) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 616
   at ClassicUO.Engine.Render() in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Engine.cs:line 761
   at ClassicUO.Engine.Tick() in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Engine.cs:line 719
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Run(String[] args) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Engine.cs:line 320
   at ClassicUO.Bootstrap.Main(String[] args) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Main.cs:line 25
ClassicUO [dev] - v0.1.2.0
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.GameObjects.Mobile.DrawInternal(UltimaBatcher2D batcher, Mobile owner, Item entity, Int32 x, Int32 y, Boolean mirror, SByte frameIndex, Boolean hasShadow, UInt16 id, Boolean isParent) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\GameObjects\Views\MobileView.cs:line 266
   at ClassicUO.Game.GameObjects.Mobile.DrawCharacter(UltimaBatcher2D batcher, Int32 posX, Int32 posY) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\GameObjects\Views\MobileView.cs:line 227
   at ClassicUO.Game.GameObjects.Mobile.Draw(UltimaBatcher2D batcher, Int32 posX, Int32 posY) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\GameObjects\Views\MobileView.cs:line 54
   at ClassicUO.Game.Scenes.GameScene.DrawWorld(UltimaBatcher2D batcher) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 669
   at ClassicUO.Game.Scenes.GameScene.Draw(UltimaBatcher2D batcher) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 616
   at ClassicUO.Engine.Render() in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Engine.cs:line 761
   at ClassicUO.Engine.Tick() in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Engine.cs:line 719
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Run(String[] args) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Engine.cs:line 320
   at ClassicUO.Bootstrap.Main(String[] args) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Main.cs:line 25






ClassicUO [dev] - v0.1.2.0
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.GameObjects.Mobile.DrawInternal(UltimaBatcher2D batcher, Mobile owner, Item entity, Int32 x, Int32 y, Boolean mirror, SByte frameIndex, Boolean hasShadow, UInt16 id, Boolean isParent) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\GameObjects\Views\MobileView.cs:line 266
   at ClassicUO.Game.GameObjects.Mobile.DrawCharacter(UltimaBatcher2D batcher, Int32 posX, Int32 posY) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\GameObjects\Views\MobileView.cs:line 227
   at ClassicUO.Game.GameObjects.Mobile.Draw(UltimaBatcher2D batcher, Int32 posX, Int32 posY) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\GameObjects\Views\MobileView.cs:line 54
   at ClassicUO.Game.Scenes.GameScene.DrawWorld(UltimaBatcher2D batcher) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 669
   at ClassicUO.Game.Scenes.GameScene.Draw(UltimaBatcher2D batcher) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 616
   at ClassicUO.Engine.Render() in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Engine.cs:line 761
   at ClassicUO.Engine.Tick() in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Engine.cs:line 719
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Run(String[] args) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Engine.cs:line 320
   at ClassicUO.Bootstrap.Main(String[] args) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Main.cs:line 25
ClassicUO [dev] - v0.1.2.0
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.GameObjects.Mobile.DrawInternal(UltimaBatcher2D batcher, Mobile owner, Item entity, Int32 x, Int32 y, Boolean mirror, SByte frameIndex, Boolean hasShadow, UInt16 id, Boolean isParent) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\GameObjects\Views\MobileView.cs:line 266
   at ClassicUO.Game.GameObjects.Mobile.DrawCharacter(UltimaBatcher2D batcher, Int32 posX, Int32 posY) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\GameObjects\Views\MobileView.cs:line 227
   at ClassicUO.Game.GameObjects.Mobile.Draw(UltimaBatcher2D batcher, Int32 posX, Int32 posY) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\GameObjects\Views\MobileView.cs:line 54
   at ClassicUO.Game.Scenes.GameScene.DrawWorld(UltimaBatcher2D batcher) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 669
   at ClassicUO.Game.Scenes.GameScene.Draw(UltimaBatcher2D batcher) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Game\Scenes\GameScene.cs:line 616
   at ClassicUO.Engine.Render() in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Engine.cs:line 761
   at ClassicUO.Engine.Tick() in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Engine.cs:line 719
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Run(String[] args) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Engine.cs:line 320
   at ClassicUO.Bootstrap.Main(String[] args) in C:\Users\Mangar\Downloads\ClassicUO-dev\src\Main.cs:line 25

**Comment by andreakarasho** [comment]
these crashes are related to other stuff. 
At this point i need to see in game with your files

**Comment by Djeryv** [comment]
Before you go down that road, I will explain a bit more about this client I am using. It is a 2D 7.0.15.1 client that I had to increase the memory of the exe to run past the 2GB limits. I did this because I loaded a bunch of custom animations to the game and the game would not load unless I increased the memory limit. Other things in this client are custom maps, items, colors, and sounds...along with those skill changes I already mentioned.

So when I load up ClassicUO, it will give me errors about missing UOP files. I had to take out the UOP files when using Classic UO because it would try to use those files for single-click names and monster animations which didn't work on the version of RunUO I am using. ClassicUO also complains that my mapdifs should be greater than 0...but they are 0 because they would mess with my custom map otherwise.

Now the client runs fine with normal UO/Razor and has for years, but I am wondering if we are beating a dead horse here with some of these issues. Meaning, maybe Classic UO is working just fine for 99.9% of the other shards/clients and mine may have these little nuances brought on by myself.

Also, ClassicUO is in a very playable state for me. When I remove the UOP files, I can single click things and get the proper names because ClassicUO will use my tiledata.mul at that point...which is what I want...and the monsters don't get overwritten by the UOP files like medusas. 

If you do want to pursue this, however, you can get the entire client and server from the link below:

https://www.servuo.com/archive/ultima-odyssey.1117/

**Comment by andreakarasho** [comment]
The main issue has been fixed
