### ISSUE TITLE
Crash to Desktop on Death

### ISSUE THREAD

**Issue by brandonclyon** [ClassicUO/ClassicUO#562]
Multiple accounts, multiple characters, when dying the client crashes to the desktop. 

Using the latest stable release.

**Comment by andreakarasho** [comment]
Crash log please

**Comment by brandonclyon** [comment]
ClassicUO [dev] - v0.0.1.11
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Exception:
System.OverflowException: Value was either too large or too small for a UInt16.
   at System.UInt16.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at ClassicUO.Game.Graphic.Parse(String str) in D:\Progetti\ClassicUO\client\src\Game\Graphic.cs:line 103
   at ClassicUO.Game.UI.Controls.ResizePic..ctor(List`1 parts) in D:\Progetti\ClassicUO\client\src\Game\UI\Controls\ResizePic.cs:line 62
   at ClassicUO.Game.Managers.UIManager.Create(Serial sender, Serial gumpID, Int32 x, Int32 y, String layout, String[] lines) in D:\Progetti\ClassicUO\client\src\Game\Managers\UIManager.cs:line 488
   at ClassicUO.Network.PacketHandlers.OpenCompressedGump(Packet p) in D:\Progetti\ClassicUO\client\src\Network\PacketHandlers.cs:line 3449
   at ClassicUO.Network.PacketHandlers.OnPacket(Object sender, Packet p) in D:\Progetti\ClassicUO\client\src\Network\PacketHandlers.cs:line 92
   at ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in D:\Progetti\ClassicUO\client\src\Utility\Exstentions.cs:line 45
   at ClassicUO.Network.NetClient.Update() in D:\Progetti\ClassicUO\client\src\Network\NetClient.cs:line 243
   at ClassicUO.Engine.OnNetworkUpdate(Double totalMS, Double frameMS) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 821
   at ClassicUO.Engine.Tick() in D:\Progetti\ClassicUO\client\src\Engine.cs:line 690
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Run(String[] args) in D:\Progetti\ClassicUO\client\src\Engine.cs:line 319
   at ClassicUO.Bootstrap.Main(String[] args) in D:\Progetti\ClassicUO\client\src\Main.cs:line 26

**Comment by Belialzao** [comment]
Latest dev is v0.1.2.98, you are on  v0.0.1.11

**Comment by brandonclyon** [comment]
I am using the latest alpha from 17 days ago. https://github.com/andreakarasho/ClassicUO/releases

**Comment by Belialzao** [comment]
https://ci.appveyor.com/project/andreakarasho/classicuo/build/artifacts

**Comment by andreakarasho** [comment]
Fixed in dev
