### ISSUE TITLE
Crash using latest dev (commit: 03b9d5a6cb95e82baa77d9a59f2a508989d00f58)

### ISSUE THREAD

**Issue by binff04** [ClassicUO/ClassicUO#614]
```
ClassicUO [dev] - v0.1.2.0
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.Renderer.UltimaBatcher2D.DrawCharacterSitted(Texture2D texture, Int32 x, Int32 y, Boolean mirror, Single h3mod, Single h6mod, Single h9mod, Vector3& hue) in C:\Users\mel\Dev\uo\ClassicUO\src\Renderer\Batcher2D.cs:line 533
   at ClassicUO.Game.GameObjects.Mobile.DrawInternal(UltimaBatcher2D batcher, Mobile owner, Item entity, Int32 x, Int32 y, Boolean mirror, SByte frameIndex, Boolean hasShadow, UInt16 id, Boolean isParent) in C:\Users\mel\Dev\uo\ClassicUO\src\Game\GameObjects\Views\MobileView.cs:line 433
   at ClassicUO.Game.GameObjects.Mobile.DrawCharacter(UltimaBatcher2D batcher, Int32 posX, Int32 posY) in C:\Users\mel\Dev\uo\ClassicUO\src\Game\GameObjects\Views\MobileView.cs:line 229
   at ClassicUO.Game.GameObjects.Mobile.Draw(UltimaBatcher2D batcher, Int32 posX, Int32 posY) in C:\Users\mel\Dev\uo\ClassicUO\src\Game\GameObjects\Views\MobileView.cs:line 83
   at ClassicUO.Game.Scenes.GameScene.DrawWorld(UltimaBatcher2D batcher) in C:\Users\mel\Dev\uo\ClassicUO\src\Game\Scenes\GameScene.cs:line 650
   at ClassicUO.Game.Scenes.GameScene.Draw(UltimaBatcher2D batcher) in C:\Users\mel\Dev\uo\ClassicUO\src\Game\Scenes\GameScene.cs:line 596
   at ClassicUO.Engine.Render() in C:\Users\mel\Dev\uo\ClassicUO\src\Engine.cs:line 749
   at ClassicUO.Engine.Tick() in C:\Users\mel\Dev\uo\ClassicUO\src\Engine.cs:line 705
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Run(String[] args) in C:\Users\mel\Dev\uo\ClassicUO\src\Engine.cs:line 323
   at ClassicUO.Bootstrap.Main(String[] args) in C:\Users\mel\Dev\uo\ClassicUO\src\Main.cs:line 26
```

**Comment by binff04** [comment]
Happened when I was running around player houses with a lot of vendor mobiles.

**Comment by andreakarasho** [comment]
fixed in dev
