### ISSUE TITLE
client crash when opening rewards gump

### ISSUE THREAD

**Issue by ziox-b** [ClassicUO/ClassicUO#696]
Crash log.

ClassicUO [dev] - v0.1.2.541
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at ClassicUO.Game.Managers.UIManager.Create(Serial sender, Serial gumpID, Int32 x, Int32 y, String layout, String[] lines) in c:\projects\classicuo\src\Game\Managers\UIManager.cs:line 322
   at ClassicUO.Network.PacketHandlers.OpenCompressedGump(Packet p) in c:\projects\classicuo\src\Network\PacketHandlers.cs:line 3608
   at ClassicUO.Network.PacketHandlers.OnPacket(Object sender, Packet p) in c:\projects\classicuo\src\Network\PacketHandlers.cs:line 81
   at ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in c:\projects\classicuo\src\Utility\Exstentions.cs:line 48
   at ClassicUO.Network.NetClient.Update() in c:\projects\classicuo\src\Network\NetClient.cs:line 235
   at ClassicUO.Engine.OnNetworkUpdate(Double totalMS, Double frameMS) in c:\projects\classicuo\src\Engine.cs:line 811
   at ClassicUO.Engine.Tick() in c:\projects\classicuo\src\Engine.cs:line 672
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Run(String[] args) in c:\projects\classicuo\src\Engine.cs:line 323
   at ClassicUO.Bootstrap.Main(String[] args) in c:\projects\classicuo\src\Main.cs:line 36

**Comment by andreakarasho** [comment]
Hi, shard?

**Comment by ziox-b** [comment]
OSI

**Comment by andreakarasho** [comment]
should be fixed
