### ISSUE TITLE
11th Oct Nightly crashing on ClassicUO.Network.PacketHandlers.DeleteObject(Packet p)

### ISSUE THREAD

**Issue by omgpointless** [ClassicUO/ClassicUO#761]
**Describe the bug**
Crashes to desktop. Happens more often around places with alot of mobiles.

**To Reproduce**
1. Go to an active boss room, or place with people. Run around and it'll crash soon enough.

**Expected behavior**
Not crashing

**Screenshots**
.
**Desktop (please complete the following information):**
 ClassicUO [dev] - v0.1.2.636
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Network.PacketHandlers.DeleteObject(Packet p) in c:\projects\classicuo\src\Network\PacketHandlers.cs:line 760
   at ClassicUO.Network.PacketHandlers.OnPacket(Object sender, Packet p) in c:\projects\classicuo\src\Network\PacketHandlers.cs:line 79
   at ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in c:\projects\classicuo\src\Utility\Exstentions.cs:line 47
   at ClassicUO.Network.NetClient.Update() in c:\projects\classicuo\src\Network\NetClient.cs:line 235
   at ClassicUO.Engine.OnNetworkUpdate(Double totalMS, Double frameMS) in c:\projects\classicuo\src\Engine.cs:line 813
   at ClassicUO.Engine.Tick() in c:\projects\classicuo\src\Engine.cs:line 677
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Run(String[] args) in c:\projects\classicuo\src\Engine.cs:line 336
   at ClassicUO.Bootstrap.Main(String[] args) in c:\projects\classicuo\src\Main.cs:line 35
**Additional context**

**Comment by andreakarasho** [comment]
fixed
