### ISSUE TITLE
Crash on first load. Could not find a suitable audio device.

### ISSUE THREAD

**Issue by skewskewskew** [ClassicUO/ClassicUO#793]
**Describe the bug**
When launching ClassicUO.exe, the application gives a message stating "Could not find a suitable audio device" and then crashes.

**To Reproduce**
1. Install ClassicUO via PowerShell command line as outlined here: http://uorforum.com/threads/classicuo-an-open-source-ultima-online-classic-client.43851/
2. Run ClassicUO.exe

**Expected behavior**
Game to launch.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Client: 0.1.2.686

**Crash Log**
```
ClassicUO [dev] - v0.1.2.686
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Exception:
Microsoft.Xna.Framework.Audio.NoAudioHardwareException (0x80004005): External component has thrown an exception.
   at Microsoft.Xna.Framework.Audio.SoundEffect.Device()
   at Microsoft.Xna.Framework.Audio.SoundEffectInstance..ctor(SoundEffect parent)
   at Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance..ctor(Int32 sampleRate, AudioChannels channels)
   at ClassicUO.IO.Audio.Sound.GetNewInstance(Boolean asEffect) in c:\projects\classicuo\src\IO\Audio\Sound.cs:line 202
   at ClassicUO.IO.Audio.Sound.Play(Boolean asEffect, AudioEffects effect, Single volume, Boolean spamCheck) in c:\projects\classicuo\src\IO\Audio\Sound.cs:line 132
   at ClassicUO.Game.Managers.AudioManager.PlayMusic(Int32 music) in c:\projects\classicuo\src\Game\Managers\AudioManager.cs:line 102
   at ClassicUO.Game.Scenes.LoginScene.Load() in c:\projects\classicuo\src\Game\Scenes\LoginScene.cs:line 97
   at ClassicUO.Engine.LoadContent() in c:\projects\classicuo\src\Engine.cs:line 644
   at Microsoft.Xna.Framework.Game.Initialize()
   at ClassicUO.Engine.Initialize() in c:\projects\classicuo\src\Engine.cs:line 637
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Engine.Run(String[] args) in c:\projects\classicuo\src\Engine.cs:line 336
   at ClassicUO.Bootstrap.Main(String[] args) in c:\projects\classicuo\src\Main.cs:line 36
```

**Comment by andreakarasho** [comment]
unfortunately this looks like a framework error [FNA].
Here https://github.com/FNA-XNA/FNA you can report that issue
