### ISSUE TITLE
Crash upon restocking

### ISSUE THREAD

**Issue by jfmeachum** [ClassicUO/ClassicUO#839]
Used RestockAgent on a chest and crashed.

**To Reproduce**
Seems random, after repeated restocking from a treasure chest.

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
Crash log:
```
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Assistant.RestockAgent.DoRestock()
   at Assistant.Timer.Slice()
   at ClassicUO.Network.Plugin.Tick() in c:\projects\classicuo\src\Network\Plugin.cs:line 293
   at ClassicUO.GameController.Update(GameTime gameTime) in c:\projects\classicuo\src\GameController.cs:line 248
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Bootstrap.Main(String[] args) in c:\projects\classicuo\src\Main.cs:line 123
```

**Comment by andreakarasho** [comment]
This is not a cuo issue. Open an issue here https://github.com/markdwags/Razor
