### ISSUE TITLE
Crash when opening a NPC vendor shop gump

### ISSUE THREAD

**Issue by Agetian** [ClassicUO/ClassicUO#904]
**Describe the bug**
[This happened when playing the Ultima Odyssey server ClassicUO package]
When opening one of the NPC animal trainers' "Buy" shop gump, the game crashes with the following debug information:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.UI.Gumps.ShopGump.ShopItem..ctor(Item item) in c:\projects\classicuo\src\Game\UI\Gumps\ShopGump.cs:line 441
   at ClassicUO.Game.UI.Gumps.ShopGump.AddItem(Item item, Boolean fromcliloc) in c:\projects\classicuo\src\Game\UI\Gumps\ShopGump.cs:line 237
   at ClassicUO.Network.PacketHandlers.OpenContainer(Packet p) in c:\projects\classicuo\src\Network\PacketHandlers.cs:line 1040
   at ClassicUO.Network.PacketHandlers.OnPacket(Object sender, Packet p) in c:\projects\classicuo\src\Network\PacketHandlers.cs:line 81
   at ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) in c:\projects\classicuo\src\Utility\Exstentions.cs:line 48
   at ClassicUO.Network.NetClient.Update() in c:\projects\classicuo\src\Network\NetClient.cs:line 232
   at ClassicUO.GameController.OnNetworkUpdate(Double totalMS, Double frameMS) in c:\projects\classicuo\src\GameController.cs:line 375
   at ClassicUO.GameController.Update(GameTime gameTime) in c:\projects\classicuo\src\GameController.cs:line 251
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()

```

**To Reproduce**
This was tested on Ultima Odyssey (latest version), it happens consistently in Lodoria City Animal Trainer NPC, opening the "Buy" shop gump consistently crashes with that same error. This is the first NPC vendor for which it happens consistently for me, so I'm not sure how to repro it with other vendors and/or on other shards. Also, not entirely sure if it's the shard issue only or if it's indicative f a more generic problem with the ClassicUO code in general, but at least it doesn't crash when using the original client 7.0.15.1 that comes with Odyssey.

**Expected behavior**
The game should not crash. When testing it with the original client 7.0.15.1 that came with Ultima Odyssey, it works correctly without crashing (and doesn't show any signs of corrupt or missing graphics in the shop gump when it's open).

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.2 with Mono 6.6.0, also tested on Windows version.
 - Tested with the current upstream "Dev" branch build and with the latest released 0.1.2.2 beta.

**Comment by Agetian** [comment]
This also happens with the Vet NPC in the building next to the Animal Trainer NPC, so it basically seems related to animals, potentially when custom animals are present?

**Comment by andreakarasho** [comment]
Where can i login to test it?

**Comment by Agetian** [comment]
Ultima Odyssey is a custom shard package released for download over here:  https://www.servuo.com/archive/ultima-odyssey.1117/

There's a server package and a ClassicUO client package available for download in the overview. A little later I'll post the exact sextant coordinates for the NPCs that consistently crash for me.

**Comment by Agetian** [comment]
Here are the steps I'd take to try to test it:

1. Download the server and the ClassicUO package from the link above.
2. Connect to the localhost using the downloaded client, login as Wizard (with the password "admin"), it should give you admin rights on the shard.
3. Teleport to (2089 2152 0) in TerMur facet (known as Lodoria on that shard), talk to the Elf Vet and open his Buy gump. For me, the game would crash at that point.

**Comment by Agetian** [comment]
(the only thing is, you may want to teleport an ordinary character in there - the admin character is invisible and apparently can't interact with the NPC vendors)

At any rate, tried the latest build from AppVeyor but that doesn't fix the crash for me, it still crashes...

**Comment by Agetian** [comment]
It looks like direction.Frames[0] is the object that is null at the point of crash.

**Comment by andreakarasho** [comment]
i see.
Pushed a fix to avoid crash, but texture still unavailable. I'll try to figure it out

**Comment by Agetian** [comment]
Tested the latest fix and I can confirm that it doesn't crash anymore. The texture for a creature named "desert ostard" is missing, as you pointed out, but otherwise the game functions normally (and I can purchase that creature and it looks normal in the game). Thanks for the fix! :)
