### ISSUE TITLE
A player speaking Thai will crash ClassicUO

### ISSUE THREAD

**Issue by Reetus** [ClassicUO/ClassicUO#925]
If you speak in Thai, a player nearby speaks it, or if it's displayed in a gump (Shop Name), ClassicUO will crash.

`
######################## [START LOG] ########################
ClassicUO [DEV_BUILD] - 0.1.2.1195
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Protocol: CF_RE, CF_TD, CF_LBR, CF_AOS, CF_SE, CF_SA
ClientFeatures: CLF_CONTEXT_MENU, CLF_PALADIN_NECROMANCER_TOOLTIPS, CLF_6_CHARACTER_SLOT, CLF_SAMURAI_NINJA, CLF_ELVEN_RACE, CLF_7_CHARACTER_SLOT
ClientLockedFeatures: TheSecondAge, Renaissance, LordBlackthornsRevenge, AgeOfShadows, SameraiEmpire, MondainsLegacy, Splash9, CharacterSlot7, EleventhAge, StygianAbyss, GothicHousing, RusticHousing
ClientVersion: 117452544

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.IO.Resources.FontsLoader.GeneratePixelsUnicode(FontTexture& texture, Byte font, String str, UInt16 color, Byte cell, Int32 width, TEXT_ALIGN_TYPE align, UInt16 flags, Boolean saveHitmap) in c:\projects\classicuo\src\IO\Resources\FontsLoader.cs:line 1117
   at ClassicUO.Renderer.RenderedText.CreateTexture() in c:\projects\classicuo\src\Renderer\RenderedText.cs:line 278
   at ClassicUO.Renderer.RenderedText.set_Text(String value) in c:\projects\classicuo\src\Renderer\RenderedText.cs:line 161
   at ClassicUO.Game.UI.AbstractEntry.set_Text(String value) in c:\projects\classicuo\src\Game\UI\AbstractEntry.cs:line 75
   at ClassicUO.Game.UI.TextEntry.SetText(String text) in c:\projects\classicuo\src\Game\UI\TextEntry.cs:line 204
   at ClassicUO.Game.UI.TextEntry.InsertString(String c) in c:\projects\classicuo\src\Game\UI\TextEntry.cs:line 136
   at ClassicUO.GameController.HandleSDLEvent(SDL_Event& e) in c:\projects\classicuo\src\GameController.cs:line 532
   at ClassicUO.GameController.OnSDLEvent(SDL_Event& ev) in c:\projects\classicuo\src\GameController.cs:line 412
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Client.Run() in c:\projects\classicuo\src\Client.cs:line 77
   at ClassicUO.Bootstrap.Main(String[] args) in c:\projects\classicuo\src\Main.cs:line 161
######################## [END LOG] ########################
`

**Comment by andreakarasho** [comment]
fixed in dev
