### ISSUE TITLE
Crash on the run

### ISSUE THREAD

**Issue by Arutosio** [ClassicUO/ClassicUO#963]
**Describe the bug**
Game Client version: 1.26.4b
this is the error file log
[2020-03-01_09-26-59_crash.txt](https://github.com/andreakarasho/ClassicUO/files/4272406/2020-03-01_09-26-59_crash.txt)

**To Reproduce**
1. dobleclick ClassicUO to run it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
**Additional context**

**Comment by roxya** [comment]
He gave me his verdata.mul and it causes this:

> System.NullReferenceException: 'Object reference not set to an instance of an object.'
> 
> ClassicUO.IO.Resources.TileDataLoader.Instance.get.Entries was null.

**Comment by roxya** [comment]
Another user just posted the same crash log for 2.0.3 client

######################## [START LOG] ########################
ClassicUO [STANDARD_BUILD] - 0.1.3.200
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Protocol: CF_RE
ClientFeatures: 0
ClientLockedFeatures: 0
ClientVersion: 33555200

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.IO.UOFileManager.Load() in D:\Progetti\ClassicUO\client\src\IO\UOFileManager.cs:line 92
   at ClassicUO.Client.Load() in D:\Progetti\ClassicUO\client\src\Client.cs:line 135
   at ClassicUO.GameController.LoadContent() in D:\Progetti\ClassicUO\client\src\GameController.cs:line 101
   at Microsoft.Xna.Framework.Game.Initialize()
   at ClassicUO.GameController.Initialize() in D:\Progetti\ClassicUO\client\src\GameController.cs:line 96
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Client.Run() in D:\Progetti\ClassicUO\client\src\Client.cs:line 52
   at ClassicUO.Bootstrap.Main(String[] args) in D:\Progetti\ClassicUO\client\src\Main.cs:line 155
######################## [END LOG] ########################

**Comment by andreakarasho** [comment]
Looks like in that installation there is not tiledata.mul

**Comment by roxya** [comment]
There is but

> 22:16:10 |  Trace   | Loading file:             D:\client-1-26-4\texidx.mul
**22:16:10 |  Trace   | Unloaded:         D:\client-1-26-4\tiledata.mul**
22:16:10 |  Trace   | Loading file:             D:\client-1-26-4\light.mul

**Comment by andreakarasho** [comment]
File size?

**Comment by roxya** [comment]
tiledata.mul 0.98 MB (1,036,288 bytes)

Mine is from OSI 1.26.4i

**Comment by Arutosio** [comment]
look this video @andreakarasho [Video of Crash ClassicUO](https://puu.sh/FgcBM/bc84f2d6a8.mp4)

**Comment by andreakarasho** [comment]
I found the issue. I’ll fix it soon as possible.

**Comment by Arutosio** [comment]
@andreakarasho thanks dude, i wait the new update for ClassicUO to release my shard :D

**Comment by andreakarasho** [comment]
should be fixed
