### ISSUE TITLE
Ultimalive Crash

### ISSUE THREAD

**Issue by popoverde** [ClassicUO/ClassicUO#978]
We got ultimalive installed on a small shard, not sure if missing something or a installation step

when trying to log with CUO it crash, heres the crashlog:

######################## [START LOG] ########################
ClassicUO [STANDARD_BUILD] - 0.1.3.0
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Protocol: CF_RE, CF_TD, CF_LBR, CF_AOS, CF_SE
ClientFeatures: 0
ClientLockedFeatures: 0
ClientVersion: CV_6000

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.IO.UltimaLive.OnUltimaLivePacket(Packet p)
   at ClassicUO.Network.PacketHandlers.OnPacket(Object sender, Packet p)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender)
   at ClassicUO.Network.NetClient.Update()
   at ClassicUO.GameController.OnNetworkUpdate(Double totalMS, Double frameMS)
   at ClassicUO.GameController.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Client.Run()
   at ClassicUO.Bootstrap.Main(String[] args)
######################## [END LOG] ########################

**Comment by SaschaKP** [comment]
Let me reassume a SIMPLE rule, MAP must have to be consequential, you can't create with ultimalive map 0x99, because in that case you must have also map from 0x0 to 0x98, so, your map must be a consequential of the last map you already have on the server

**Comment by popoverde** [comment]
That makes sense, the map number its 34 by itself, so changing it to... 8 should fix it i suppose

**Comment by SaschaKP** [comment]
yep, so that's the case, you can create as many maps as you want, but maps must have to be +1 of the last actual existing map on your client/server files.

Also, consider a mod on your server, when changing map (onmapchange) put a requestclienthash to renew client files (servuo and runuo don't have it, but it's a required mod). Come talk to discord if you need some help (SOME, not everything :D )
