### ISSUE TITLE
Unicode characters crash WorldMap

### ISSUE THREAD

**Issue by brndd** [ClassicUO/ClassicUO#980]
WorldMap causes a crash when displaying unicode characters (in this case, a character name with the letter `ä` in it).

```
######################## [START LOG] ########################
ClassicUO [STANDARD_BUILD] - 0.1.3.200
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Protocol: CF_RE, CF_TD, CF_LBR, CF_AOS, CF_SE
ClientFeatures: 0
ClientLockedFeatures: TheSecondAge, Renaissance, LordBlackthornsRevenge, AgeOfShadows, EleventhAge
ClientVersion: 83886345

Exception:
System.ArgumentException: Text contains characters that cannot be resolved by this SpriteFont.
Parameter name: text
   at ClassicUO.Renderer.SpriteFont.MeasureString(String text) in C:\Users\eru\Documents\GitHub\ClassicUO\src\Renderer\SpriteFont.cs:line 99
   at ClassicUO.Game.UI.Gumps.WorldMapGump.DrawWMEntity(UltimaBatcher2D batcher, WMapEntity entity, Int32 x, Int32 y, Int32 width, Int32 height, Single zoom) in C:\Users\eru\Documents\GitHub\ClassicUO\src\Game\UI\Gumps\WorldMapGump.cs:line 720
   at ClassicUO.Game.UI.Gumps.WorldMapGump.DrawAll(UltimaBatcher2D batcher, Int32 gX, Int32 gY, Int32 halfWidth, Int32 halfHeight) in C:\Users\eru\Documents\GitHub\ClassicUO\src\Game\UI\Gumps\WorldMapGump.cs:line 543
   at ClassicUO.Game.UI.Gumps.WorldMapGump.Draw(UltimaBatcher2D batcher, Int32 x, Int32 y) in C:\Users\eru\Documents\GitHub\ClassicUO\src\Game\UI\Gumps\WorldMapGump.cs:line 495
   at ClassicUO.Game.Managers.UIManager.Draw(UltimaBatcher2D batcher) in C:\Users\eru\Documents\GitHub\ClassicUO\src\Game\Managers\UIManager.cs:line 817
   at ClassicUO.GameController.Draw(GameTime gameTime) in C:\Users\eru\Documents\GitHub\ClassicUO\src\GameController.cs:line 332
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Client.Run() in C:\Users\eru\Documents\GitHub\ClassicUO\src\Client.cs:line 52
   at ClassicUO.Bootstrap.Main(String[] args) in C:\Users\eru\Documents\GitHub\ClassicUO\src\Main.cs:line 157
######################## [END LOG] ########################
```

**Comment by andreakarasho** [comment]
pushed a fix. Let me know!
